repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.47.0
      hooks:
        -   id: markdownlint
            args: ["--fix"]

ci:
  autoupdate_schedule: monthly
